<?php

use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_user_login().
 */
function intranet_helper_user_login($account) {
  if (Drupal::request()->query->get('redirect')) {
    global $base_root;

    // Set redirect headers to Drupal response.
    $response = new RedirectResponse($base_root);
    $response->send();
  }
}

/**
 * Implements hook_user_logout().
 */
function intranet_helper_user_logout($account) {
  // Check out user.
  \Drupal::service('intranet_helper.services.api')->checkUserOut(Drupal::request(), $account->id());

  if (Drupal::request()->query->get('redirect')) {
    global $base_root;

    // Set redirect headers to Drupal response.
    $response = new RedirectResponse($base_root);
    $response->send();
  }
}
