---
vagrantfile-local:
    vm:
        box: ubuntu14.04
        box_url: 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
        hostname: null
        network:
            private_network: 192.168.93.187
            forwarded_port:
                CocLsFE7aIwA:
                    host: '8098'
                    guest: '80'
                CocLsFE7aIwE:
                    host: '8099'
                    guest: '3306'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '4024'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            lxc:
                box: fgrehm/precise64-lxc
                box_url: https://atlas.hashicorp.com/fgrehm/boxes/precise64-lxc/versions/1.2.0/providers/lxc.box
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            8Q9vTs08YuK2:
                source: ./
                target: /var/www
                nfs: 'true'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - vim
        - htop
        - git
        - php5-memcached
        - memcached
        - unzip
        - libaugeas-dev
        - libaugeas-ruby
        - imagemagick
        - php5-imagick
    dot_files:
        - bash_aliases: null
    _prevent_empty: ''
