name: 'Intranet config storage'
description: 'Config storage module that contains sidewide configurations.'
package: Intranet
type: module
version: 1.0
core: 8.x

dependencies:
  - intranet_helper
  - intranet_fields
  - path
  - rest
  - datetime
  - entity_reference
  - title
  - user
