<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;;

/**
 * Implements hook_views_query_alter().
 */
function intranet_holidays_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'holidays') {
    $query->where[1]['conditions'][2]['field'] = str_replace('%Y-%m-%d', '%Y', $query->where[1]['conditions'][2]['field']);
    $query->where[1]['conditions'][3]['field'] = str_replace('%Y-%m-%d', '%Y', $query->where[1]['conditions'][3]['field']);
  }
}
