---
# This playbook installs apache

- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  sudo: yes

  vars:
    apache_listen_port: 80
    apache_create_vhosts: true
    apache_vhosts_filename: "vhosts.conf"
    apache_vhosts:
      - {
        servername: "drupal.d8pp.dev",
        documentroot: "/var/www/drupal"
      }
      - {
        servername: "angular.d8pp.dev",
        documentroot: "/var/www/angular/www"
      }
    apache_mods_enabled:
      - rewrite.load
      - headers.load
      - ssl.load

  roles:
    - { role: ansible-role-apache }
